git config --global --unset alias.initten 
git config --global --unset alias.clonen 
git config --global --unset alias.pullen 
git config --global --unset alias.adden 
git config --global --unset alias.pushen 
git config --global --unset alias.pfuschen
git config --global --unset alias.branchen 
git config --global --unset alias.commiten 
git config --global --unset alias.rebasen 
git config --global --unset alias.diffen 
git config --global --unset alias.mergen 
git config --global --unset alias.stashen 
git config --global --unset alias.taggen 
git config --global --unset alias.auschecken 
git config --global --unset alias.protokoll 
git config --global --unset alias.zustand 
git config --global --unset alias.blamen 
git config --global --unset alias.fetchen 
git config --global --unset alias.forken 
git config --global --unset alias.cherry-picken
