git config --global alias.initten init
git config --global alias.clonen clone
git config --global alias.pullen pull
git config --global alias.adden add
git config --global alias.pushen push
git config --global alias.pfuschen 'push --force'
git config --global alias.branchen branch
git config --global alias.commiten commit
git config --global alias.rebasen rebase
git config --global alias.diffen diff
git config --global alias.mergen merge
git config --global alias.stashen stash
git config --global alias.taggen tag
git config --global alias.auschecken checkout
git config --global alias.protokoll log
git config --global alias.zustand status
git config --global alias.blamen blame
git config --global alias.fetchen fech
git config --global alias.forken fork
git config --global alias.cherry-picken cherry-pick
